export const FN_EVENT_AUTH_LOGIN_SUCCESS =
  "FN_EVENT_AUTH_LOGIN_SUCCESS" as const;
export const FN_EVENT_AUTH_LOGOUT = "FN_EVENT_AUTH_LOGOUT" as const;
export const FN_EVENT_AUTH_LOGIN_FAILURE =
  "FN_EVENT_AUTH_LOGIN_FAILURE" as const;
export const FN_EVENT_AUTH_SESSION_IP_DRIFT =
  "FN_EVENT_AUTH_SESSION_IP_DRIFT" as const;
export const FN_EVENT_SECURITY_SCANNER_BLOCKED =
  "FN_EVENT_SECURITY_SCANNER_BLOCKED" as const;
export const FN_EVENT_DDNS_UPDATE_COMPLETED =
  "FN_EVENT_DDNS_UPDATE_COMPLETED" as const;
export const FN_EVENT_GATEWAY_THROTTLE_BLOCKED =
  "FN_EVENT_GATEWAY_THROTTLE_BLOCKED" as const;
export const FN_EVENT_WAF_BLOCKED = "FN_EVENT_WAF_BLOCKED" as const;
export const FN_EVENT_SSH_LOGIN_SUCCESS = "FN_EVENT_SSH_LOGIN_SUCCESS" as const;
export const FN_EVENT_SSH_LOGIN_FAILURE = "FN_EVENT_SSH_LOGIN_FAILURE" as const;
export const FN_EVENT_SSH_IP_BLOCKED = "FN_EVENT_SSH_IP_BLOCKED" as const;
export const FN_EVENT_SYSTEM_APP_UPDATE_AVAILABLE =
  "FN_EVENT_SYSTEM_APP_UPDATE_AVAILABLE" as const;
export const FN_EVENT_SYSTEM_CPU_ALERT = "FN_EVENT_SYSTEM_CPU_ALERT" as const;
export const FN_EVENT_SYSTEM_CPU_RECOVERED =
  "FN_EVENT_SYSTEM_CPU_RECOVERED" as const;
export const FN_EVENT_SYSTEM_MEMORY_ALERT =
  "FN_EVENT_SYSTEM_MEMORY_ALERT" as const;
export const FN_EVENT_SYSTEM_MEMORY_RECOVERED =
  "FN_EVENT_SYSTEM_MEMORY_RECOVERED" as const;
export const FN_EVENT_TUNNEL_FRP_CONNECTED =
  "FN_EVENT_TUNNEL_FRP_CONNECTED" as const;
export const FN_EVENT_TUNNEL_FRP_DISCONNECTED =
  "FN_EVENT_TUNNEL_FRP_DISCONNECTED" as const;
export const FN_EVENT_TUNNEL_CLOUDFLARED_CONNECTED =
  "FN_EVENT_TUNNEL_CLOUDFLARED_CONNECTED" as const;
export const FN_EVENT_TUNNEL_CLOUDFLARED_DISCONNECTED =
  "FN_EVENT_TUNNEL_CLOUDFLARED_DISCONNECTED" as const;

export const SYSTEM_EVENT_TYPES = [
  FN_EVENT_AUTH_LOGIN_SUCCESS,
  FN_EVENT_AUTH_LOGOUT,
  FN_EVENT_AUTH_LOGIN_FAILURE,
  FN_EVENT_AUTH_SESSION_IP_DRIFT,
  FN_EVENT_SECURITY_SCANNER_BLOCKED,
  FN_EVENT_DDNS_UPDATE_COMPLETED,
  FN_EVENT_GATEWAY_THROTTLE_BLOCKED,
  FN_EVENT_WAF_BLOCKED,
  FN_EVENT_SSH_LOGIN_SUCCESS,
  FN_EVENT_SSH_LOGIN_FAILURE,
  FN_EVENT_SSH_IP_BLOCKED,
  FN_EVENT_SYSTEM_APP_UPDATE_AVAILABLE,
  FN_EVENT_SYSTEM_CPU_ALERT,
  FN_EVENT_SYSTEM_CPU_RECOVERED,
  FN_EVENT_SYSTEM_MEMORY_ALERT,
  FN_EVENT_SYSTEM_MEMORY_RECOVERED,
  FN_EVENT_TUNNEL_FRP_CONNECTED,
  FN_EVENT_TUNNEL_FRP_DISCONNECTED,
  FN_EVENT_TUNNEL_CLOUDFLARED_CONNECTED,
  FN_EVENT_TUNNEL_CLOUDFLARED_DISCONNECTED,
] as const;

export type SystemEventType = (typeof SYSTEM_EVENT_TYPES)[number];

export const FN_EVENT_LEVEL_INFO = "INFO" as const;
export const FN_EVENT_LEVEL_WARN = "WARN" as const;
export const FN_EVENT_LEVEL_ERROR = "ERROR" as const;
export const FN_EVENT_LEVEL_CRITICAL = "CRITICAL" as const;

export const SYSTEM_EVENT_LEVELS = [
  FN_EVENT_LEVEL_INFO,
  FN_EVENT_LEVEL_WARN,
  FN_EVENT_LEVEL_ERROR,
  FN_EVENT_LEVEL_CRITICAL,
] as const;

export type SystemEventLevel = (typeof SYSTEM_EVENT_LEVELS)[number];

export const SYSTEM_EVENT_SOURCE_SERVER_ADMIN = "SERVER_ADMIN" as const;
export const SYSTEM_EVENT_SOURCE_GO_REAUTH_PROXY = "GO_REAUTH_PROXY" as const;
export const SYSTEM_EVENT_SOURCE_SYSTEM_MONITOR = "SYSTEM_MONITOR" as const;

export const SYSTEM_EVENT_SOURCES = [
  SYSTEM_EVENT_SOURCE_SERVER_ADMIN,
  SYSTEM_EVENT_SOURCE_GO_REAUTH_PROXY,
  SYSTEM_EVENT_SOURCE_SYSTEM_MONITOR,
] as const;

export type SystemEventSource = (typeof SYSTEM_EVENT_SOURCES)[number];

export const SYSTEM_EVENT_SUBJECT_KIND_IP = "IP" as const;
export const SYSTEM_EVENT_SUBJECT_KIND_SESSION = "SESSION" as const;
export const SYSTEM_EVENT_SUBJECT_KIND_DDNS = "DDNS" as const;
export const SYSTEM_EVENT_SUBJECT_KIND_RESOURCE = "RESOURCE" as const;
export const SYSTEM_EVENT_SUBJECT_KIND_APPLICATION = "APPLICATION" as const;
export const SYSTEM_EVENT_SUBJECT_KIND_TUNNEL = "TUNNEL" as const;

export const SYSTEM_EVENT_SUBJECT_KINDS = [
  SYSTEM_EVENT_SUBJECT_KIND_IP,
  SYSTEM_EVENT_SUBJECT_KIND_SESSION,
  SYSTEM_EVENT_SUBJECT_KIND_DDNS,
  SYSTEM_EVENT_SUBJECT_KIND_RESOURCE,
  SYSTEM_EVENT_SUBJECT_KIND_APPLICATION,
  SYSTEM_EVENT_SUBJECT_KIND_TUNNEL,
] as const;

export type SystemEventSubjectKind =
  (typeof SYSTEM_EVENT_SUBJECT_KINDS)[number];

export const isSystemEventType = (value: string): value is SystemEventType =>
  (SYSTEM_EVENT_TYPES as readonly string[]).includes(value);

export const isSystemEventLevel = (value: string): value is SystemEventLevel =>
  (SYSTEM_EVENT_LEVELS as readonly string[]).includes(value);

export const isSystemEventSource = (
  value: string,
): value is SystemEventSource =>
  (SYSTEM_EVENT_SOURCES as readonly string[]).includes(value);

export const isSystemEventSubjectKind = (
  value: string,
): value is SystemEventSubjectKind =>
  (SYSTEM_EVENT_SUBJECT_KINDS as readonly string[]).includes(value);
